---
- name: Setup classroom environment
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: Check if user is logged in via GUI
      register: login_type
      changed_when: false
      ansible.builtin.shell: >
        loginctl show-session $(loginctl --no-legend | awk '{print $1}') -p Type --value

    - name: Terminate playbook if user is not logged in via GUI
      ansible.builtin.assert:
        that: >
          'x11' in login_type['stdout'] or 'wayland' in login_type['stdout']
        fail_msg: |
          ⛔️  ️    ⛔️      ⛔️      ⛔️      ⛔️      ⛔️      ⛔️      ⛔️

          This playbook must be run from a console session at
          https://rol.redhat.com

          ⛔️  ️    ⛔️      ⛔️      ⛔️      ⛔️      ⛔️      ⛔️      ⛔️

    - name: Ensure needed packages are installed
      become: true
      ansible.builtin.dnf:
        name:
          - sqlite
          - "https://gitlab.com/gitlab-org/cli/-/releases/v1.47.0/downloads/glab_1.47.0_linux_amd64.rpm"
        state: installed
        disable_gpg_check: true

    - name: Ensure pip3 is installed with python 3.11
      register: pip3_output
      ansible.builtin.command: /usr/bin/python3 -m ensurepip
      changed_when: >
        'Requirement already satisfied' not in pip3_output['stdout']

    - name: Ensure needed python packages are installed
      ansible.builtin.pip:
        name: yamllint
        state: present
        extra_args: --user

    - name: Ensure needed directories are present
      loop: "{{ dir_list }}"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory

    - name: Ensure pathogen is downloaded
      ansible.builtin.get_url:
        url: https://tpo.pe/pathogen.vim
        dest: ~/.vim/autoload/pathogen.vim

    - name: Ensure plugin repos are cloned
      loop: "{{ repo_list }}"
      ansible.builtin.git:
        repo: "{{ item }}"
        dest: ~/.vim/bundle/{{ item.split('/')[-1] | regex_replace('\.git$') }}

    - name: Render terminal profile template
      notify: Ensure profile is loaded
      ansible.builtin.template:
        src: terminal_profile.j2
        dest: /var/tmp/terminal_profile
        mode: 0644

    - name: Ensure config files are copied
      loop: "{{ lookup('dict', config_files) }}"
      notify: Ensure terminal terminates
      ansible.builtin.copy:
        src: "{{ item['value']['file'] }}"
        dest: "{{ item['value']['dest'] }}"

    - name: Ensure /etc/bashrc is configured
      become: true
      ansible.builtin.blockinfile:
        path: /etc/bashrc
        block: "{{ my_bashrc }}"
        state: present

    - name: Ensure ~/.ssh/config is configured
      ansible.builtin.blockinfile:
        path: ~/.ssh/config
        block: "{{ my_sshconfig }}"
        state: present

    - name: Ensure /etc/bash_completion.d/glab is configured
      become: true
      ansible.builtin.shell: >
        glab completion -s bash > /etc/bash_completion.d/glab
      args:
        creates: /etc/bash_completion.d/glab

    - name: Ensure my git config is set (mail)
      tags:
        - never
        - ricardo
      community.general.git_config:
        name: user.email
        scope: global
        value: rgdacosta@gmail.com

    - name: Ensure my git config is set (name)
      tags:
        - never
        - ricardo
      community.general.git_config:
        name: user.name
        scope: global
        value: Ricardo da Costa

    - name: Ensure my git config is set (credentials cache)
      tags:
        - never
        - ricardo
      community.general.git_config:
        name: credential.helper
        scope: global
        value: "cache --timeout=10800"

    - name: Ensure lab timings cronjob is enabled
      ansible.builtin.cron:
        name: "Send lab data to api"
        minute: "0"
        hour: "17"
        job: ~/bin/upload_timings

    - name: Ensure resolution is obtained
      register: current_resolution
      changed_when: false
      ansible.builtin.command: xrandr

    - name: Ensure resolution is set
      when: "'current 1920 x 1080' not in current_resolution['stdout']"
      ansible.builtin.command: xrandr --size 1920x1080

    - name: Ensure firefox configuration tasks are included
      ansible.builtin.include_tasks:
        file: tasks/firefox.yml

    - name: Create an Alt + Tab alternative with Alt + q
      ansible.builtin.shell: >
        gsettings set org.gnome.desktop.wm.keybindings switch-windows "['<Alt>q']"
      changed_when: false
      when: "'<Alt>q' not in lookup('pipe', 'gsettings get org.gnome.desktop.wm.keybindings switch-windows')"

  handlers:
    # community.general.dconf was considered but did not behave as expected
    - name: Ensure profile is loaded
      ansible.builtin.shell: dconf load /org/gnome/terminal/ < /var/tmp/terminal_profile
      args:
        creates: /var/tmp/terminal_profile_loaded

    - name: Ensure terminal terminates
      ansible.builtin.command: killall gnome-terminal-server
      when: "'gnome-terminal-server' in lookup('pipe', 'pgrep -l gnome-terminal-server')"
