---
bootloader_settings:
  - kernel: ALL
    options:
      - name: video=1920x1080
        state: present

ansible_python_interpreter: /usr/bin/python3
ansible_become_password: student

system_dir_list:
  - /usr/share/vim/vimfiles/pack/vendor/start
  - /usr/share/vim/vimfiles/pack/vendor/opt

config_files:

  vim:
    file: vimrc
    dest: ~/.vimrc
    perms: '0644'

  nano:
    file: nanorc
    dest: ~/.nanorc
    perms: '0644'

  tmux:
    file: tmux.conf
    dest: ~/.tmux.conf
    perms: '0644'

  monitor:
    file: monitors.xml
    dest: ~/.config/monitors.xml
    perms: '0644'

  terminal:
    file: org.gnome.Terminal.desktop
    dest: ~/.local/share/applications/org.gnome.Terminal.desktop
    perms: '0644'

  ansible-navigator:
    file: ansible-navigator.yml
    dest: ~/.ansible-navigator.yml
    perms: '0644'


regularfont_uuid: F69A6B60-AD40-4530-84E1-F8260A26B40C
mediumfont_uuid: 76A4B99C-AFAC-4DE5-B0B2-C433303F1699
largefont_uuid: F28FF536-5DA1-4C8B-BE71-B38F5B51653F

classroom_env_motd: |
  #!/bin/bash
  if [ -t 1 ] && [ -z "$SSH_CONNECTION" ]; then
  cat <<'EOF'
  *******************************************************************
  *                                                                 *
  *   I now have a wiki to showcase the features of this project!   *
  *                                                                 *
  *   https://gitlab.com/rgdacosta/classroom_env/-/wikis/home       *
  *                                                                 *
  *                                                                 *
  *   rdacosta@redhat.com                                           *
  *                                                                 *
  *   To get rid of this message use:                               *
  *                                                                 *
  *   sudo rm -f /etc/profile.d/classroom_env.sh                    *
  *                                                                 *
  *******************************************************************
  EOF
  fi
