ansible_python_interpreter: /usr/bin/python3 
ansible_become_password: student

dir_list:
  - ~/.vim/autoload
  - ~/.vim/bundle
  - ~/.config/yamllint
  - ~/bin

repo_list:
  - https://github.com/Yggdroot/indentLine.git
  - https://github.com/pedrohdz/vim-yaml-folds.git
  - https://github.com/dense-analysis/ale.git
  - https://tpope.io/vim/commentary.git

config_files:

  nano:
    file: nanorc
    dest: ~/.nanorc
    perms: '0644'

  yamllint:
    file: config
    dest: ~/.config/yamllint/config
    perms: '0644'

  tmux:
    file: tmux.conf
    dest: ~/.tmux.conf
    perms: '0644'

  monitor:
    file: monitors.xml
    dest: ~/.config/monitors.xml
    perms: '0644'

  terminal:
    file: org.gnome.Terminal.desktop
    dest: ~/.local/share/applications/org.gnome.Terminal.desktop
    perms: '0644'

  ansible-navigator:
    file: ansible-navigator.yml
    dest: ~/.ansible-navigator.yml
    perms: '0644'

regularfont_uuid: "{{ lookup('pipe', 'uuidgen') }}" 
mediumfont_uuid: "{{ lookup('pipe', 'uuidgen') }}"
largefont_uuid: "{{ lookup('pipe', 'uuidgen') }}"
