ansible_python_interpreter: /usr/bin/python3
ansible_become_password: student

rpm_packages:
  - "https://gitlab.com/gitlab-org/cli/-/releases/v1.47.0/downloads/glab_1.47.0_linux_amd64.rpm"
  - sqlite

python_packages:
  - yamllint
  - ansible-lint

system_dir_list:
  - /usr/share/vim/vimfiles/pack/vendor/start
  - /usr/share/vim/vimfiles/pack/vendor/opt

vim_plugins_list:
  - https://github.com/Yggdroot/indentLine.git
  - https://github.com/pedrohdz/vim-yaml-folds.git
  - https://github.com/dense-analysis/ale.git
  - https://tpope.io/vim/commentary.git
  - https://github.com/vim-airline/vim-airline.git
  - https://github.com/pearofducks/ansible-vim.git

config_files:

  vim:
    file: vimrc
    dest: ~/.vimrc
    perms: '0644'

  nano:
    file: nanorc
    dest: ~/.nanorc
    perms: '0644'

  tmux:
    file: tmux.conf
    dest: ~/.tmux.conf
    perms: '0644'

  monitor:
    file: monitors.xml
    dest: ~/.config/monitors.xml
    perms: '0644'

  terminal:
    file: org.gnome.Terminal.desktop
    dest: ~/.local/share/applications/org.gnome.Terminal.desktop
    perms: '0644'

  ansible-navigator:
    file: ansible-navigator.yml
    dest: ~/.ansible-navigator.yml
    perms: '0644'

regularfont_uuid: F69A6B60-AD40-4530-84E1-F8260A26B40C
mediumfont_uuid: 76A4B99C-AFAC-4DE5-B0B2-C433303F1699
largefont_uuid: F28FF536-5DA1-4C8B-BE71-B38F5B51653F
