vim_plugins_list:
  - https://github.com/Yggdroot/indentLine.git
  - https://github.com/pedrohdz/vim-yaml-folds.git
  - https://github.com/dense-analysis/ale.git
  - https://tpope.io/vim/commentary.git
  - https://github.com/vim-airline/vim-airline.git
  - https://github.com/towolf/vim-helm.git
  - https://github.com/ntpeters/vim-better-whitespace.git
  - https://github.com/jiangmiao/auto-pairs.git
  - https://github.com/tpope/vim-fugitive.git
  - https://github.com/sheerun/vim-polyglot.git
