---
zerotier_interface: "{{ ansible_facts['interfaces'] | select('match', '^zt') | list | first }}"

lab_networks:
  - "172.25.250.0/24"
  - "192.168.50.0/24"

lab_gateway: "172.25.250.253"
zerotier_source: "10.147.20.0/24"